# Generated by Django 4.2.19 on 2026-02-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clsProductos',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('tipoproducto', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('precioxm', models.CharField(blank=True, max_length=2, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblproductos',
                'managed': False,
            },
        ),
    ]
