# Generated by Django 4.2.19 on 2026-02-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTSM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clsDetalleVenta',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tbldetalleventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='clsVentas',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'tblventas',
                'managed': False,
            },
        ),
    ]
