# Generated by Django 4.2.19 on 2026-02-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clsUsuarios',
            fields=[
                ('idusuario', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Identificacion')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('contrasena', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('correo', models.CharField(max_length=255, verbose_name='Correo')),
                ('activo', models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=25, null=True, verbose_name='Activo')),
                ('token', models.CharField(blank=True, max_length=25, null=True, verbose_name='Token')),
                ('cambiocontrasena', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'tblusuarios',
                'managed': False,
            },
        ),
    ]
